name: Test

on:
  push:
    branches: [ master, load-extension ]
  pull_request:
    branches: [ master, load-extension ]

jobs:
  linux:
    name: Test on OTP ${{ matrix.otp_version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        otp_version: [25,26,27,28]
        os: [ubuntu-latest]

    container:
      image: erlang:${{ matrix.otp_version }}

    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: make
      - name: Test
        run: make test
